"""empty message

Revision ID: 6c2f012c02f8
Revises: 
Create Date: 2024-04-25 14:25:13.030958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2f012c02f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('player_id', 'players', ['player_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
